---
title: "Von Ingenieuren und Romanistikerinnen"
subtitle: "Die Entwicklung des Frauenanteils unter den Studierenden von 1998 bis 2017"
author: "Roman Link und Kerstin Pierick"
date: "March 9, 2019"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Das Thema

Frauenanteil in Studiengängen 1998 bis 2017

 - "Klassischen Männer- und Frauenfächer" immer noch männlich/weiblich dominiert?
 - Entwicklung des Frauenanteils in der Zeit - unterschiedliche Entwicklungen in den Studiengängen?
     - Abhängigkeit des zeitlichen Effekts vom Frauenanteil zum Ausgangszeitpunkt?
 - Sonderstellung der MINT-Fächer?
  
 
## Die Daten

- Quelle: Statistisches Bundesamt Deutschland (www.destatis.de) 

- Struktur: 
    - Alle Hochschulen Deutschlands
    - Jahre 1998-2017
    - Aufgeschlüsselt nach Studiengängen, Geschlecht, Nationalität (In-/Ausland), Bundesland der Hochschule
    - StudienanfängerInnen und Studierende 

 - Zusatzdaten: "Studierende an Hochschulen - Fächersystematik" (pdf)


## Datenumformung

 - Herausfiltern der benötigten Informationen: Nationalität und Bundesland nicht benötigt
 - Encoding: Korrektes Einlesen von Umlauten, leere Felder = 0 
 - Zusammenfügen von StudienanfängerInnen, Studierenden und Fächersystematik
 - Berechnen neuer Variablen (Frauenanteil)
 - Zusammenfassen nach Gruppen


## Technische Umsetzung

  - Einlesen, zusammenfügen und Umwandeln der Daten: R
  - Abbildungen: ggplot2 (R-Paket)
  - Interaktive Abbildungen: ggplotly (R-Paket)
  - HTML-Dokument mit Text und Abbildungen: R Markdown
  - Präsentation: Latex Beamer in R Markdown
  - Versionsverwaltung, Backup, Website: GitHub


## Interview mit Expertin

Angefragt: 

 - Prof. Petra Lucht, Gender Studies, TU Berlin
 - Dr. Martina Erlemann, Gender Studies/Physik, FU Berlin
 - Anna Lena Martins, Gleichstellungsbeauftragte Mathematik, Uni Göttingen
 - **Dr. Sophie-Charlotte August, Gleichstellungsbeauftragte Physik, Uni Göttingen**
 
## Recherche

 - Zeitungsartikel
 - wissenschaftliche Artikel
 - Projekte zur Förderung von Frauen in MINT-Fächern
 - Wikipedia-Artikel
 
## Das Stück

https://kerstinpierick.github.io/Studentinnen-in-MINT-Faechern/
